
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Artistic','dfgegegrger Lorem ipusum UPDATEEEEEEEEEEEEEEEEEEEEE kjhjghjg  loreeeeeee','Festival Music','Music,Pop,Opera,new',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Meals','skdfjslkfdjflfsjlsfjfkldsfldsklf','Arabian Food','Foot,Restaurant,Italian Food,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Vacations','mslkjflkjsdlfjdsfjdfkldsjflfjdskfsdfljdsjflskdfjdljdlk','Dream travel vactions','Airplane,Tourism,Beach,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Blogs','dskfjsdfjkdsfjsldfjslkfjsdfjsdjfjdkfjdsljlflksjjfksnns,dnas','Some blog','Blog,Other tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Food','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Movies','fdsfsdfdffsfs','LASTEST CINEMA MOVIES','accion,suspense,drama',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Artistic','dfgegegrger Lorem ipusum UPDATEEEEEEEEEEEEEEEEEEEEE kjhjghjg  loreeeeeee','Festival Music','Music,Pop,Opera,new',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Meals','skdfjslkfdjflfsjlsfjfkldsfldsklf','Arabian Food','Foot,Restaurant,Italian Food,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Vacations','mslkjflkjsdlfjdsfjdfkldsjflfjdskfsdfljdsjflskdfjdljdlk','Dream travel vactions','Airplane,Tourism,Beach,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Blogs','dskfjsdfjkdsfjsldfjslkfjsdfjsdjfjdkfjdsljlflksjjfksnns,dnas','Some blog','Blog,Other tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Food','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Movies','fdsfsdfdffsfs','LASTEST CINEMA MOVIES','accion,suspense,drama',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Artistic','dfgegegrger Lorem ipusum UPDATEEEEEEEEEEEEEEEEEEEEE kjhjghjg  loreeeeeee','Festival Music','Music,Pop,Opera,new',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Meals','skdfjslkfdjflfsjlsfjfkldsfldsklf','Arabian Food','Foot,Restaurant,Italian Food,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Vacations','mslkjflkjsdlfjdsfjdfkldsjflfjdskfsdfljdsjflskdfjdljdlk','Dream travel vactions','Airplane,Tourism,Beach,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Blogs','dskfjsdfjkdsfjsldfjslkfjsdfjsdjfjdkfjdsljlflksjjfksnns,dnas','Some blog','Blog,Other tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Food','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Movies','fdsfsdfdffsfs','LASTEST CINEMA MOVIES','accion,suspense,drama',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Artistic','dfgegegrger Lorem ipusum UPDATEEEEEEEEEEEEEEEEEEEEE kjhjghjg  loreeeeeee','Festival Music','Music,Pop,Opera,new',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Meals','skdfjslkfdjflfsjlsfjfkldsfldsklf','Arabian Food','Foot,Restaurant,Italian Food,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Vacations','mslkjflkjsdlfjdsfjdfkldsjflfjdskfsdfljdsjflskdfjdljdlk','Dream travel vactions','Airplane,Tourism,Beach,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Blogs','dskfjsdfjkdsfjsldfjslkfjsdfjsdjfjdkfjdsljlflksjjfksnns,dnas','Some blog','Blog,Other tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Food','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Movies','fdsfsdfdffsfs','LASTEST CINEMA MOVIES','accion,suspense,drama',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Artistic','dfgegegrger Lorem ipusum UPDATEEEEEEEEEEEEEEEEEEEEE kjhjghjg  loreeeeeee','Festival Music','Music,Pop,Opera,new',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Meals','skdfjslkfdjflfsjlsfjfkldsfldsklf','Arabian Food','Foot,Restaurant,Italian Food,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Vacations','mslkjflkjsdlfjdsfjdfkldsjflfjdskfsdfljdsjflskdfjdljdlk','Dream travel vactions','Airplane,Tourism,Beach,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Blogs','dskfjsdfjkdsfjsldfjslkfjsdfjsdjfjdkfjdsljlflksjjfksnns,dnas','Some blog','Blog,Other tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Food','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Movies','fdsfsdfdffsfs','LASTEST CINEMA MOVIES','accion,suspense,drama',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Artistic','dfgegegrger Lorem ipusum UPDATEEEEEEEEEEEEEEEEEEEEE kjhjghjg  loreeeeeee','Festival Music','Music,Pop,Opera,new',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Meals','skdfjslkfdjflfsjlsfjfkldsfldsklf','Arabian Food','Foot,Restaurant,Italian Food,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Vacations','mslkjflkjsdlfjdsfjdfkldsjflfjdskfsdfljdsjflskdfjdljdlk','Dream travel vactions','Airplane,Tourism,Beach,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Blogs','dskfjsdfjkdsfjsldfjslkfjsdfjsdjfjdkfjdsljlflksjjfksnns,dnas','Some blog','Blog,Other tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Food','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Movies','fdsfsdfdffsfs','LASTEST CINEMA MOVIES','accion,suspense,drama',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Artistic','dfgegegrger Lorem ipusum UPDATEEEEEEEEEEEEEEEEEEEEE kjhjghjg  loreeeeeee','Festival Music','Music,Pop,Opera,new',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Meals','skdfjslkfdjflfsjlsfjfkldsfldsklf','Arabian Food','Foot,Restaurant,Italian Food,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Vacations','mslkjflkjsdlfjdsfjdfkldsjflfjdskfsdfljdsjflskdfjdljdlk','Dream travel vactions','Airplane,Tourism,Beach,Relax',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Blogs','dskfjsdfjkdsfjsldfjslkfjsdfjsdjfjdkfjdsljlflksjjfksnns,dnas','Some blog','Blog,Other tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Food','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Movies','fdsfsdfdffsfs','LASTEST CINEMA MOVIES','accion,suspense,drama',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Science','fdsfsdfdffsfs','Some blog','Tag',NULL);
INSERT INTO `blog` (`category`,`content`,`title`,`tags`) VALUES ('Clothes','fsfsfsdfsffewrweruwieruwifjsdjfsf','Some blogs 2','Blogs,Blogs',NULL);

